[global]
keyboard = "en-us"
country = "de"
fqdn = {{FQDN}}
mailto = {{EMAIL}}
timezone = {{TIMEZONE}}
root_password = {{ROOT_PASSWORD}}
reboot_on_error = false

[network]
source = "from-dhcp"

[disk-setup]
filesystem = "zfs"
disk_list = ["/dev/vda", "/dev/vdb"]
zfs.raid = "raid1"
zfs.checksum = "fletcher4"
zfs.compress = "lz4"
zfs.hdsize = 850
